// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __FLEX_EVENTS__
#define __FLEX_EVENTS__


// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"




const EmberEventData emAppEvents[] = {
  {NULL, NULL}
};
#endif // __FLEX_EVENTS__
