// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __FLEX_BOOKKEEPING_H__
#define __FLEX_BOOKKEEPING_H__



#endif // __FLEX_BOOKKEEPING_H__
