#include "em_timer.h"
#include "em_adc.h"
#include "em_gpio.h"
#include "InitDevice.h"

#include "rail.h"

#include "FreeRTOS.h"
#include "queue.h"

#include "dsp.h"

#include <stdio.h>

/* Signal flow during reception
 * ----------------------------
 * Audio output is a PWM output driven by a timer.
 * I/Q input is read from the RAIL RX FIFO.
 * Audio output sample rate should have a known relationship
 * to the I/Q input sample rate.
 * To ensure the input and output streams keep synchronized, they
 * are driven by the same interrupt handler, which is the
 * RAIL RX FIFO event callback handler.
 * Every time a block of I/Q samples is received, one audio sample
 * is updated to the PWM value. Thus, the I/Q sample rate should
 * be an integer multiple of the audio sample rate.
 *
 * To avoid jitter and aliasing effects, the audio sample rate
 * should be synchronized to the PWM frequency, so that each
 * audio sample affects a constant number of PWM cycles.
 * Some attention should be paid to the effect of interrupt
 * timing jitter in updating the PWM value.
 * (This part is not done yet.)
 *
 * Software interfaces
 * -------------------
 * The callback handler interfaces to the fast DSP task
 * through a ring buffer and an RTOS queue.
 * Each queue item contains the number of samples to process
 * and pointers to input and output buffers.
 * The fast DSP task calls dsp_fast_rx with these buffers
 * to do the actual signal processing.
 * The fast DSP task can further defer processing to the
 * slow DSP task by buffering data and sending messages
 * using an RTOS queue.
 *
 * Signal flow during transmission
 * -------------------------------
 * Audio input comes from the integrated ADC.
 * Transmitted signal is generated by writing the channel register
 * of the frequency synthesizer, so a frequency modulated signal
 * is transmitted.
 * Both the audio input and frequency modulation output are
 * handled in the ADC interrupt handler, and they have the same
 * sampling rate.
 *
 */

/* -------------------------
 * Buffer size configuration
 * ------------------------- */

/* Ratio of I/Q input and audio output sample rates.
 * This determines the number of samples to read
 * at a time from the RAIL FIFO. */
#define RX_SAMPLE_RATIO 2

/* How many samples to process at a time in the DSP task.
 * This is the number of audio samples, so number of I/Q
 * samples is RX_SAMPLE_RATIO times the value. */
#define RX_DSP_BLOCK 32

/* Size of the RX ring buffer as a multiple of block size. */
#define RX_BUF_BLOCKS 2

/* How many transmit samples to process at a time */
#define TX_DSP_BLOCK 32

/* Size of the TX ring buffer as a multiple of block size. */
#define TX_BUF_BLOCKS 2


/* ----------------------
 * Buffers and data types
 * ---------------------- */

/* Diagnostics, could be moved to some more global place */
struct diagnostics {
	uint32_t rx_blocks_overflow, rx_blocks_isr, rx_blocks_task;
	uint32_t rx_rail_underruns, rx_samples_isr;
	uint32_t tx_blocks_overflow, tx_blocks_isr, tx_blocks_task;

	// Cycle counters to estimate CPU usage of fast DSP
	uint32_t cycles_dsp, cycles_nodsp;
};
struct diagnostics diag;


/* Receive-related buffers */
audio_out_t buf_audio_out[RX_DSP_BLOCK * RX_BUF_BLOCKS];
iq_in_t buf_iq_in[RX_DSP_BLOCK * RX_BUF_BLOCKS * RX_SAMPLE_RATIO];
unsigned rx_buf_p = 0;

/* Transmit-related buffers */
audio_in_t buf_audio_in[TX_DSP_BLOCK * TX_BUF_BLOCKS];
fm_out_t buf_fm_out[TX_DSP_BLOCK * TX_BUF_BLOCKS];
unsigned tx_buf_p = 0;

/* Message sent from interrupt to fast DSP task during receive */
struct fast_dsp_rx_msg {
	iq_in_t *in;
	audio_out_t *out;
	uint16_t in_len, out_len;
};

/* Message sent from interrupt to fast DSP task during transmit */
struct fast_dsp_tx_msg {
	audio_in_t *in;
	fm_out_t *out;
	uint16_t len;
};

/* Queues to communicate between interrupts and fast DSP task */
QueueHandle_t fast_dsp_rx_q, fast_dsp_tx_q;
QueueSetHandle_t fast_dsp_qs;


/* ----------------
 * Driver functions
 * ---------------- */

/* rail_callback is called from a RAIL interrupt handler */
void rail_callback(RAIL_Handle_t rail, RAIL_Events_t events)
{
	BaseType_t yield = 0;
	if (events & RAIL_EVENT_RX_FIFO_ALMOST_FULL) {
		unsigned nread, p = rx_buf_p;
		TIMER_CompareBufSet(TIMER0, 0, buf_audio_out[p]);
		nread = RAIL_ReadRxFifo(rail, (uint8_t*)(buf_iq_in + p * RX_SAMPLE_RATIO), sizeof(iq_in_t) * RX_SAMPLE_RATIO);
		if (nread != sizeof(iq_in_t) * RX_SAMPLE_RATIO)
			++diag.rx_rail_underruns;
		++diag.rx_samples_isr;

		if (p % RX_DSP_BLOCK == RX_DSP_BLOCK - 1) {
			// Index of the first sample in the latest received block
			unsigned fp = p - (RX_DSP_BLOCK - 1);

			struct fast_dsp_rx_msg msg = {
				buf_iq_in + fp * RX_SAMPLE_RATIO,
				buf_audio_out + fp,
				RX_DSP_BLOCK * RX_SAMPLE_RATIO,
				RX_DSP_BLOCK
			};
			if (xQueueSendFromISR(fast_dsp_rx_q, &msg, &yield))
				++diag.rx_blocks_isr;
			else
				++diag.rx_blocks_overflow;
		}

		if (++p >= RX_DSP_BLOCK * RX_BUF_BLOCKS)
			p = 0;
		rx_buf_p = p;
	}
	portYIELD_FROM_ISR(yield);
}


/* Set frequency synthesizer channel */
static inline void synth_set_channel(uint32_t ch)
{
	*(uint32_t*)0x40083038 = ch;
}


/* ADC interrupt, used for transmission */
void ADC0_IRQHandler() {
	BaseType_t yield = 0;
	unsigned p = tx_buf_p;
	synth_set_channel(buf_fm_out[p]);
	buf_audio_in[p] = ADC0->SINGLEDATA;

	if (p % TX_DSP_BLOCK == TX_DSP_BLOCK - 1) {
		unsigned fp = p - (TX_DSP_BLOCK - 1);

		struct fast_dsp_tx_msg msg = {
			buf_audio_in + fp,
			buf_fm_out + fp,
			TX_DSP_BLOCK
		};
		if (xQueueSendFromISR(fast_dsp_tx_q, &msg, &yield))
			++diag.tx_blocks_isr;
		else
			++diag.tx_blocks_overflow;
	}

	if (++p >= TX_DSP_BLOCK * TX_BUF_BLOCKS)
		p = 0;
	tx_buf_p = p;

	ADC_IntClear(ADC0, ADC_IF_SINGLE);
	portYIELD_FROM_ISR(yield);
}


int start_rx_dsp(RAIL_Handle_t rail)
{
	// TODO clear the audio buffer for first round
	unsigned r;
#ifdef MIC_EN_PIN
	GPIO_PinOutClear(MIC_EN_PORT, MIC_EN_PIN);
#endif
	ADC_IntDisable(ADC0, ADC_IF_SINGLE);
	RAIL_ResetFifo(rail, false, true);
	RAIL_SetRxFifoThreshold(rail, sizeof(iq_in_t) * RX_SAMPLE_RATIO);
	r = RAIL_StartRx(rail, 32, NULL);
	printf("RAIL_StartRx: %u\n", r);
	return r;
}


int start_tx_dsp(RAIL_Handle_t rail)
{
	(void)rail;
	// TODO clear the FM buffer for first round
#ifdef MIC_EN_PIN
	GPIO_PinOutSet(MIC_EN_PORT, MIC_EN_PIN);
#endif
	NVIC_EnableIRQ(ADC0_IRQn);
	ADC_IntEnable(ADC0, ADC_IF_SINGLE);
	ADC_Start(ADC0, adcStartSingle);
	return 0;
}


/* Create the RTOS objects needed by DSP.
 * Called before starting the scheduler. */
void dsp_rtos_init(void)
{
	fast_dsp_rx_q = xQueueCreate(RX_BUF_BLOCKS - 1, sizeof(struct fast_dsp_rx_msg));
	fast_dsp_tx_q = xQueueCreate(TX_BUF_BLOCKS - 1, sizeof(struct fast_dsp_tx_msg));
	fast_dsp_qs = xQueueCreateSet(RX_BUF_BLOCKS - 1 + TX_BUF_BLOCKS - 1);
	xQueueAddToSet(fast_dsp_rx_q, fast_dsp_qs);
	xQueueAddToSet(fast_dsp_tx_q, fast_dsp_qs);
}


void fast_dsp_task(void *arg)
{
	(void)arg;
	uint32_t cyc1, cyc2;
	dsp_update_params();
	cyc2 = DWT->CYCCNT;
	for (;;) {
		QueueHandle_t q;
		q = xQueueSelectFromSet(fast_dsp_qs, portMAX_DELAY);
		cyc1 = DWT->CYCCNT;
		diag.cycles_nodsp += cyc1 - cyc2;
		if (q == fast_dsp_rx_q) {
			struct fast_dsp_rx_msg msg;
			if (xQueueReceive(q, &msg, 0)) {
				dsp_fast_rx(msg.in, msg.in_len, msg.out, msg.out_len);
				++diag.rx_blocks_task;
			}
		} else if (q == fast_dsp_tx_q) {
			struct fast_dsp_tx_msg msg;
			if (xQueueReceive(q, &msg, 0)) {
				dsp_fast_tx(msg.in, msg.out, msg.len);
				++diag.tx_blocks_task;
			}
		}
		cyc2 = DWT->CYCCNT;
		diag.cycles_dsp += cyc2 - cyc1;
	}
}
